pop-os/cosmic-files

i18n/pl/cosmic_files.ftl

Added basic Polish translation, there wasn't any so i thought it would be welcome

Add  cosmic_files.ftl PL translation

---

i18n/cs/cosmic_files.ftl

Add i18n for Czech language.

---

i18n/ru/cosmic_files.ftl
i18n/zh-cn/cosmic_files.ftl

The translations are based on the commonly used names for the corresponding fields.

translation: added i18n for the Chinese and Russian language

---

i18n/pl/cosmic_files.ftl

Updated to match EN i18n file.

Update cosmic_files.ftl PL Translation

---

i18n/pt/cosmic_files.ftl
i18n/pt_BR/cosmic_files.ftl

Added i18n for both languages with their respective preferences.
Based on Dolphin and Nautilus.

Portuguese and Brazilian Portuguese i18n files.

---

src/app.rs
src/tab.rs

Here is the next batch of unit tests and helper functions. I implemented tests for most of `Tab`'s messages. I'll work on the next batch soon. :smiley_cat:

Add Tab unit tests

---

README.md
i18n/pt/cosmic_files.ftl
i18n/pt_BR/cosmic_files.ftl

* Better Markdown for external developers
* Improved the Portuguese Translation

Improved the README.md and the Portuguese Translation

---

src/tab.rs

This pr preserves sorting when changing directories and includes minor refactors.

Refactor sorting

---

src/dialog.rs

Very small change but worth it for ergonomics.

Close dialog on escape

---

i18n/pt/cosmic_files.ftl

Update/fix/improve Portuguese `pt` translation

Update Portuguese translation

---

src/app.rs
src/dialog.rs

Update modified time on change

---

src/app.rs

It would be useful for my places status indicator applet.

Add trash flag

---

i18n/fi/cosmic_files.ftl

Add Finnish Translation

---

Cargo.lock
Cargo.toml
src/app.rs

Reload trash on changes

---

i18n/ko/cosmic_files.ftl

Added Korean Translation

---

Cargo.lock

fix: clipboard update

---

i18n/zh-TW/cosmic_files.ftl

i18n(zh_TW): add Taiwanese translation

---

Cargo.lock
Cargo.toml
i18n/en/cosmic_files.ftl
src/app.rs
src/operation.rs

closes: #135, #145
This patch is usable if anyone wishes to test it. I'm going to write a few unit tests before marking it as ready.

feat: Duplicate items to the same directory

---

i18n/en/cosmic_files.ftl
i18n/pl/cosmic_files.ftl
src/app.rs
src/config.rs
src/dialog.rs
src/menu.rs
src/tab.rs

closes https://github.com/pop-os/cosmic-files/issues/171

feat: default view config

---

i18n/de/cosmic_files.ftl

i18n (de): Update German translation

---

Cargo.lock
Cargo.toml
src/app.rs
src/key_bind.rs
src/menu.rs
src/tab.rs

Global search

---

src/app.rs

fix: activate nav bar item with matching location

---

i18n/cs/cosmic_files.ftl

Updated Czech translation based on the i18n(en) file.

i18n(cs): Translation update

---

src/app.rs

Resolves #211 
Added logic to the nav menu which not only added the "Empty Trash" button to the Trash folder in the navigation bar, but also removed the "Remove from favorites" button from Trash, which I assumed to be the intended behavior.

Added the "Empty Trash" button on the Trashes nav-menu.

---

i18n/pt-BR/cosmic_files.ftl

Aligning translation with the original file.

i18n(pt-BR) - Updating translation

---

Cargo.lock
src/app.rs
src/dialog.rs
src/key_bind.rs
src/menu.rs
src/tab.rs

* Add "Open in new tab" and "Open in new window" to context menu.
* Add bread crumb context menu with "Open in new tab", "Open in new window", and "Properties".
* Open files with middle click.
* Open directories in a new tab with middle click.
* Works in the main view.
* Works for the bread crumbs,
* Works in nav bar.
* Add key bindings to open in new tab (Ctrl + Enter) and open in new window (Shift + Enter).
Implements #261.
Implements #262.

Open in new tab/window

---

i18n/zh-TW/cosmic_files.ftl

I can't translate `replace-with = Replace with` due to word order.
In English, it will be `Replace with {something}.` (Or I misunderstanding this entry?
But in zh-TW, it would be
`使用 {something} 替換。`
So some changes are required, thank you.

Update zh-TW translations

---

src/operation.rs

fix: copy_to_diff_dir_doesnt_dupe_files hangs

---

src/tab.rs

Fixes #240.
Also fixes the condensed view details not appearing at 50% list size, and the scrollbar always being present when condensed.
Edit: Also fixes #292.

Various fixes

---

src/tab.rs

My previous PR got merged at almost the same time as this was pushed @jackpot51.

Match divider padding to design

---

i18n/de/cosmic_files.ftl

add to side bar was frogotten in the german translation in Context menu so i added it.

Add forgotten Translation for sidebar in German

---

i18n/en/cosmic_files.ftl
src/app.rs
src/key_bind.rs
src/menu.rs
src/tab.rs

Adds horizontal padding to the context menu divider, to match designs.

Add missing File menu entries

---

src/app.rs

Clear and close search field on nav buttons clicked

---

src/app.rs

Activate navbar selection on init and when switching tabs

---

i18n/fr/cosmic_files.ftl

Hello,
This update includes the latest French translations for the file manager, reflecting the most recent changes from the `cosmic_files.ftl` file in English.
Best regards,
Roxfr

Updated french translation for Cosmic Files

---

i18n/de/cosmic_files.ftl
i18n/en/cosmic_files.ftl
justfile
src/app.rs
src/tab.rs

 Display no-results message instead of empty-folder when there are no search results

---

src/tab.rs

Sort modified descending on initial click

---

src/tab.rs

Use pointer mouse cursor for breadcrumbs

---

src/app.rs
src/dialog.rs
src/tab.rs

Select previous directory when navigating back

---

Cargo.lock
Cargo.toml
i18n/en/cosmic_files.ftl
src/app.rs
src/menu.rs
src/operation.rs

Linked to https://github.com/pop-os/cosmic-files/issues/122
This adds an "Extract here" menu option for selected .zip files.

Enable extracting zip files to current folder

---

i18n/pt/cosmic_files.ftl

Adds the remaining fields and fixes some translations

i18n: Update pt translation

---

src/app.rs

Should close https://github.com/pop-os/cosmic-files/issues/252  (#252 )
Demo:
[delete-in-search-mode.webm](https://github.com/user-attachments/assets/5a11f245-14cf-475e-82b3-0e7d58466384)

Delete files in search-mode. (fix for #252)

---

i18n/sv/cosmic_files.ftl

Updated Swedish Translation 
(was unsure if the product name COSMIC Files should be Cosmic Filer instead in Swedish or not or if you translate product names or not?)

Update cosmic_files.ftl Swedish translation

---

Cargo.lock
Cargo.toml
i18n/en/cosmic_files.ftl
src/app.rs
src/menu.rs
src/operation.rs

Continuing the work I did on https://github.com/pop-os/cosmic-files/commit/ef23ff77e1442cb348901f8d6720341fb0da0685 (an Extract archive option) for https://github.com/pop-os/cosmic-files/issues/122. This PR adds a right-click option to compress files into a zip archive in the current directory, and lets you choose a new file name.

Add Compress menu option to add files to zip archive

---

i18n/it/cosmic_files.ftl

Update ITA cosmic_files.ftl

---

i18n/pl/cosmic_files.ftl

Added bits related to compress

Update cosmic_files.ftl PL translate compress

---

Cargo.lock
Cargo.toml
cosmic-files-applet/Cargo.toml
cosmic-files-applet/src/main.rs
i18n/en/cosmic_files.ftl
justfile
src/app.rs
src/dialog.rs
src/lib.rs
src/menu.rs
src/mime_app.rs
src/tab.rs

Desktop mode

---

i18n/pl/cosmic_files.ftl

Update cosmic_files.ftl PL translation Sorting

---

i18n/it/cosmic_files.ftl

Update cosmic_files.ftl italian

---

i18n/fr/cosmic_files.ftl

Hello,
Here is the update for the French language:
- Added new elements,
- Adjustments.
Regards,
Roxfr

Update cosmic_files.ftl (French)

---

i18n/pl/cosmic_files.ftl

Added network shares, permissions, fixed some language to feel more natural, removed dupes

Update cosmic_files.ftl PL translation Network

---

i18n/it/cosmic_files.ftl

Update cosmic_files.ftl ITA

---

src/app.rs
src/dialog.rs
src/tab.rs

This allows preview of images using most of the window, in both the regular app and in the dialog.

Gallery view

---

i18n/en/cosmic_files.ftl
src/menu.rs
src/tab.rs

Closes: #458
~(Will finish this tomorrow)~
It's tomorrow and it's finished. :partying_face:

Show file deletion date in Trash

---

i18n/pt-BR/cosmic_files.ftl

i18n (pt-BR) translation update

---

src/operation.rs

This pull request addresses two related issues in the extraction functionality of the application:
1. **Preserving Full Folder Names**: 
Previously, extracted folders with names containing periods before the extension (e.g., `file.last.6.4.tar.gz`) were being incorrectly named, leading to truncated folder names (e.g., `file`). This fix ensures that the full original name is preserved during extraction.
2. **Correctly Appending Copy Suffix**:
A bug was identified where, if a folder with the same name already existed, the new folder was incorrectly named with the copy suffix placed in the wrong location. For instance, a folder named `Test_File_0.5.0last` would create a new folder as `Test_File_0.5 (Copy 1).0last` instead of the expected `Test_File_0.5.0last (Copy 1)`. This issue has been …

Fix extraction folder naming issues and handle existing folders correctly

---

src/tab.rs

hide files in .hidden file

---

i18n/pl/cosmic_files.ftl

Update cosmic_files.ftl PL translation Desktop view

---

src/app.rs
src/tab.rs

Rust analyzer keeps yelling at me about that compile error, so I had to fix it for my own sanity.

Fix tests, a compile error for the Wayland feature, and a deprecation notice

---

i18n/fi/cosmic_files.ftl

- The structure of the Finnish localization file was way outdated, when compared to the English one.
- Also changed some things like a Git commit being translated as "sitoumus" instead of "versio". Way too literal of a translation.

Update Finnish localisation

---

src/mounter/gvfs.rs
src/mouse_area.rs
src/tab.rs

Really adds a lot to the interactive feel
Demo:
https://github.com/user-attachments/assets/bcf7ba74-a52a-4d29-8556-932a826bacbc

feat: Highlight items on mouse over

---

src/app.rs

[This debug assert](https://github.com/pop-os/iced/blob/29ff72bb51c09d9b57ee9126f2629361e29fc2f3/futures/src/subscription.rs#L249) makes mapping with capturing closures panic in debug mode.

fix: Make subscription map closure non-capturing

---

i18n/en/cosmic_files.ftl
i18n/it/cosmic_files.ftl
src/mounter/gvfs.rs
src/tab.rs

Directories sizes in details view

---

i18n/pl/cosmic_files.ftl

Added missing bits, hopefully it's ok

Update cosmic_files.ftl PL translation operation progress

---

examples/dialog.rs
src/app.rs
src/dialog.rs
src/menu.rs
src/tab.rs

This matches the context menu to the designs.
Just wanted to clean up the code for the dialog context drawer (thought I already tried that, and it didn't work; but I guess not), but didn't want to make such a minor PR.

[Context menu] Increase vertical item padding

---

src/app.rs

The panels should always be centered, but some apps might not be.

refactor: overlap handling for surfaces that occupy a corner

---

src/app.rs

Unset `show_details` on escape

---

src/app.rs

I didn't notice that the `close` button didn't set `show_details` until @git-f0x pointed it out. Oops.
On the bright side, this is overall cleaner since it fixes a todo.

Unset `show_details` on close too

---

i18n/th/cosmic_files.ftl

Add Thai translation string for cosmic-files

i18n(th): Add Thai translation

---

src/menu.rs

Enable `Open item location` for Recents

---

src/dialog.rs

Fix 'New folder...' context menu item in save dialog

---

src/app.rs
src/operation/mod.rs

Closes: #698
I ended up fixing a few Clippy lints while tracking down this problem. It turns out that the issue was way simpler than I assumed: ".tar.xz" needed to be added to a slice of extensions to strip.
Also, the changes in `Message::Rename` are due to rustfmt (I didn't even notice that until I opened this).

fix: Strip more file names in extractor

---

src/app.rs

Based on https://github.com/pop-os/cosmic-files/pull/711#issuecomment-2566494648
Also removes the search update within the operationComplet handler, since it should not be needed anymore.

always check if a search is active when rescanning

---

src/app.rs
src/key_bind.rs
src/tab.rs

Move to first/last item with home/end keys

---

src/app.rs
src/mime_app.rs

I left one lint untouched because it will be fixed in a TODO.

chore(clippy): `app.rs`, `mime_app.rs`

---

i18n/pl/cosmic_files.ftl

Update cosmic_files.ftl PL translation Password Grid Spacing

---

src/app.rs

fix: set the active tab in desktop mode when the window is focused

---

i18n/ga/cosmic_files.ftl

Added Irish translation to COSMIC files

(i18n) Added Irish translation

---

i18n/en/cosmic_files.ftl
src/app.rs
src/config.rs
src/tab.rs

This provides the ability to have typing when no input is focused to directly open the search input (like Ctrl+F) or the location editing input (like Ctrl+L). The default is configurable in settings.

Type to search or seek

---

src/app.rs

Update favorites when dir is renamed or moved

---

src/app.rs

Just removed imports that were no longer in use in app.rs file. Thanks.

Removed unused imports

---

i18n/en/cosmic_files.ftl
src/app.rs
src/menu.rs

The feature introduced in this PR is one mentioned in the issue #749 
That is the Extract To feature.
This is still pretty rough, but no bugs to the best of my knowledge but I'm not sure how to make it better since Cosmic Files has no file/directory picker so you'll have to manually put in the location you want to extract to.

Introduces feature mentioned in #749

---

i18n/pl/cosmic_files.ftl

Update cosmic_files.ftl PL Translation Type-to-search Delete and stuff

---

i18n/en/cosmic_files.ftl
i18n/hu/cosmic_files.ftl
i18n/nl/cosmic_files.ftl
src/app.rs

Also, fix toasts for Extract and Compress.
Closes #894
Part of #749

Use Open Folder dialog for Extract To

---

i18n/fr/cosmic_files.ftl

Update fr traduction

---

i18n/fr/cosmic_files.ftl

Complete translation based on the english file

Fr translation

---

Cargo.lock
Cargo.toml
src/app.rs
src/config.rs
src/dialog.rs
src/localize.rs
src/tab.rs

Use icu for date and time localization

---

src/mime_app.rs

Nothing too fancy. I'm more confident that `exec_to_command` works as expected after writing these tests.

Add tests for `exec_to_command`

---

src/operation/mod.rs

Fix macOS build

---

src/mime_app.rs

This uses the same method as cosmic/settings to determine the default terminal application. This is more of a quick fix for the moment, because it does not yet adhere to the rules of https://github.com/Vladimir-csp/xdg-terminal-exec (which is apparently planned)
fixes #827

feat: "Open in terminal" now respects the default terminal application

---

src/tab.rs

fixes file scaling in grid view affecting the file preview.

fix #878 (file scaling in grid view affects preview)

---

i18n/ga/cosmic_files.ftl

Translated new strings, translated network drive schemes

Updated Irish translations

---

i18n/es/cosmic_files.ftl

Updated the spanish translation to match the english version at epoch 7.

i18n(es): Updated the translation

---

i18n/en/cosmic_files.ftl
i18n/nl/cosmic_files.ftl

Notice: Changes the English source file.

i18n(nl) & i18n(en) update Dutch translation & propose adjustment in source language

---

i18n/pl/cosmic_files.ftl

Update cosmic_files.ftl PL translation permadelete

---

i18n/pl/cosmic_files.ftl

Added permission and executable bits.

Update cosmic_files.ftl PL Translation Permissions and executable

---

i18n/en/cosmic_files.ftl
src/app.rs
src/dialog.rs
src/menu.rs
src/mounter/gvfs.rs
src/tab.rs

fixes https://github.com/pop-os/cosmic-files/issues/907

fix: add eject button for context menus on mount point

---

src/app.rs
src/config.rs
src/dialog.rs
src/lib.rs
src/tab.rs

fixes https://github.com/pop-os/cosmic-files/issues/858

feat: persist sort options for each location

---

i18n/pl/cosmic_files.ftl

Update cosmic_files.ftl PL Translation Eject

---

Cargo.lock
Cargo.toml
i18n/en/cosmic_files.ftl
src/app.rs
src/menu.rs
src/operation/mod.rs

Add ability to remove files from Recents

---

Cargo.lock
Cargo.toml
src/app.rs
src/config.rs
src/lib.rs
src/menu.rs
src/mounter/gvfs.rs
src/mounter/mod.rs
src/tab.rs

Try mount favorite

---

src/mounter/gvfs.rs

should fix #581, though I am having a lot of trouble with NFS URIs specifically, but that doesn't seem to be a regression after testing on my machine.

fix: network page entries

---

examples/dialog.rs
src/config.rs
src/dialog.rs

Dialog update

---

src/app.rs
src/menu.rs

Fixes two instances where enumerating trash items isn't needed.

Use trash-rs' is_empty more

---

src/app.rs

Recursively watching the trash directories can be slow, but not watching at least the "files" folder (e.g. .Trash-1000/files) leads to missed events.
I also simplified events parsing.
----
I tested this by trashing and emptying the trash outside of COSMIC Files while watching Files for changes. So, to test:
```sh
touch blorp
gio trash blorp
```
Check COSMIC Files.
```sh
gio trash --empty
```
Check again.

Fix trash watcher regression

---

TESTING.md

Broken up into categories to make it easier to read, but I was more concerned with making the order of operations as quick as possible for testing.

docs: Add QA testing checklist

---

i18n/pl/cosmic_files.ftl

Update cosmic_files.ftl PL translate typo fix

---

src/app.rs

Fixes https://github.com/pop-os/cosmic-files/issues/1152

fix: update modifier state for all windows, not just the main window
