- i18n/sr-Cyrl/cosmic_files.ftl
- i18n/sr-Latn/cosmic_files.ftl
Unrelated to the pull request but didn't want to create a separate issue over something that isn't that important:
Perhaps the nav bar selection graphic should either be a bit longer or slightly thinner, since it's currently a kind of elongated squircle that doesn't match the pill shape present in cosmic-settings or cosmic-edit (though it had a pill shape before the `reduce width` commit, so might be better to just make it thinner). 
And perhaps the name of the Home directory in the nav bar should be just Home instead of the user name, to match other file managers.
If this was already planned or is intended, sorry for making you read all of this. Cosmic Files is starting to look pretty nice!
Edit: Just saw that the old Figma design draft has all of this, so maybe all this text was …
> i18n(sr): Update translations

- src/main.rs
This patch adds three new hot keys based on [common shortcuts](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts).
| Key combo | Description |
| --- | --- |
| `ctrl` + `w` | Close current tab. Closes cosmic-files if only one tab is open. | 
| `ctrl` + `PgUp` | Activates the next tab. Move to the first tab if the last tab is active. |
| `ctrl` + `PgDown` | Activate the prev tab. Cycles through tabs like the above key combo. |
I'll implement more key combos if this PR is deemed useful and desirable. Personally, I have a keyboard centered workflow so I always navigate with shortcuts, even on Windows. I'm sure other future users would want more shortcuts as well.
> Add keyboard shortcuts for closing and cycling tabs

- Cargo.lock
- src/main.rs
one naive attempt at addressing:
```
cosmic-files on  master_jammy is 📦 v0.1.0 via 🦀 v1.75.0
nu ❯ cargo build --release
Updating git repository `https://github.com/pop-os/client-toolkit`
Updating crates.io index
Updating git repository `https://github.com/pop-os/libcosmic.git`
Updating git submodule `https://github.com/pop-os/cosmic-design-demo`
Updating git submodule `https://github.com/pop-os/iced.git`
Updating git repository `https://github.com/jackpot51/systemicons`
Updating git repository `https://github.com/DioxusLabs/taffy`
Updating git repository `https://github.com/jackpot51/rust-atomicwrites`
Updating git repository `https://github.com/pop-os/cosmic-text.git`
error: failed to get `cosmic-text` as a dependency of package `iced_tiny_skia v0.12.0 …
```
> fix: `cargo` update to target available cosmic-text commit

- Cargo.lock
- Cargo.toml
- src/localize.rs
- src/mime_icon.rs
- src/tab.rs
1. Rust language is encouraging people to move away from lazy_static to once_cell. 
This is because once_cell will be closer to the actual standard library version [More Info](https://github.com/rust-lang-nursery/lazy-static.rs/issues/214)
2. Updates all Dependencies.
3. Updated the command for opening files on the Windows Platform. Some files were not opening. Such as video files.
> Update Depends, Fix Windows Open Bug, Remove lazy_static

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/tab.rs
I implemented a few helper functions for tests as well as three tests for `tab::scan_path`.
The helper functions create a small, temporary file hierarchy using [tempdir](https://docs.rs/tempdir/latest/tempdir/) to test file operations. I also wrote a few helpers for tasks that will likely be repeated throughout tests e.g. comparing `Item` and `Path`s.
I'll work on writing more unit tests if these are okay so far.
> Test helpers and unit tests

- src/app.rs
- src/mouse_area.rs
Not entirely sure if this will work but `app.rs` is based on #32 to hopefully avoid a conflict.
This enables support for navigation with the back/forward buttons present on some mice.
> Support going back/forward with mouse buttons

- src/app.rs
- src/config.rs
- src/dialog.rs
- src/key_bind.rs
- src/tab.rs
Fixes #24 
This works by adding a type for tab configs. The new type is passed to each tab which enables ephemeral, per tab configs. For example, a user can have hidden files visible on one tab but invisible on another.
This should make it easier to fix other TODOs such as using custom heights in `Tab::grid_view()` or different icon sizes et cetera.
> feat: Toggle showing hidden files/folders

- i18n/en/cosmic_files.ftl
- src/app.rs
- src/config.rs
- src/dialog.rs
- src/tab.rs
This PR adds modifiable icon sizes to the settings page. I represented it as a zoom level instead of pixels.
I clamped the maximum size to an arbitrary number, so that will likely need to be changed to a better value later.
Also! I added the "show hidden" option to the settings page too since I forgot to do it before. :sweat_smile:
> Tab settings page and icon sizes

- src/app.rs
Fixes (or at least improves): #39 
This doesn't close the `MenuBar` if it's opened yet because I couldn't figure out a good way to do it.
> Close context pages and tab menus on Escape

- i18n/en/cosmic_files.ftl
- src/app.rs
- src/config.rs
- src/menu.rs
- src/tab.rs
I've implemented an option to set a default sorting scheme for new tabs. This is related to but doesn't close [#149](https://github.com/pop-os/cosmic-edit/issues/149) on COSMIC Edit.
This PR also adds a feature to sort the grid view by reusing the code to sort the list view.
Finally, I've also added context menu buttons to sort the views without going to settings - this is more useful for grid view. The new context menu items are similar to what is offered in Thunar, Windows Explorer, and likely others.
> Sorter choice config + sort grid view

- i18n/ja/cosmic_files.ftl
One note about "open with": In Japanese the application name goes at the beginning (e.g. Firefoxで開く) with no way to move it to the end.  This string should use a parameter just like the default-app string to accommodate for languages that don't use SVO word order.
> Update Japanese translation

- src/app.rs
This fixes #104 . It also fixes an issue where cutting and pasting a folder onto itself deletes it.
> fix: don't allow pasted contents to include the destination.

- src/mouse_area.rs
- src/tab.rs
- Fix for extra click event. When clicking a file with the mouse, two `Click` events would get fired instead of one.
- Better ctrl + click handling. Clicking on an already selected item will deselect it on `ClickRelease`.
- Add support for drag-selecting with shift of ctrl pressed. This will now invert the selection of any items within the drag rectangle.
- Implement shift+click selection. #114
- Fix for arrow key navigation/selection after an item is clicked with the mouse. #151
- Fix a bug where drag-and-drop would sometimes get initiated inadvertently when there were files selected but you clicked and dragged in the empty area below the files. This should instead start a new drag selection.
> Selection enhancements and bug fixes

- src/app.rs
This PR allows the navigation model to activate an entity on selection.
Current:
Expected:
> fix: activate nav model entity

- src/tab.rs
This seems to have been broken by the latest libcosmic update.
> Fix drag selecting from empty area in grid view

- src/tab.rs
This fixes the scrollbar showing up when there's space below the files.
> Fix spacer height

- Cargo.lock
- Cargo.toml
- src/tab.rs
> Bump `trash-rs` to fix panic for non-Unicode paths

- src/tab.rs
When there was a single row of files and there weren't enough files to fill the row, you couldn't initiate a drag select from the right side of these files.
Fixes #238
> Fix drag select for grid view

- src/key_bind.rs
It seems the zoom in shortcut was set to 'Ctrl' + '='  to make it work better with 70% and smaller keyboards, but 'Ctrl' + '+' wasn't added.
> Add 'Ctrl' + '+' as a zoom-in shortcut

- Cargo.lock
- Cargo.toml
- src/localize.rs
- src/tab.rs
Fixes some of #256
This patch also cleans up the `icu` dependencies from my last PR. I added all of `icu` as a dependency last time because I assumed it would be needed for this fix. However, `chrono` supports localization and `icu` seemed harder to use anyway.
> Localized date strings

- src/app.rs
- src/key_bind.rs
- src/menu.rs
- src/tab.rs
Made the List view sorting headings fixed size to match the behavior of most file managers (and so that they don't become too large). The designs use 24.0 (space_m), but the text doesn't fit at that size, so 32.0 was used.
Also added some horizontal padding to the breadcrumb bar to better match the designs.
With changes:
Design:
Unrelated, but with the latest commits, it seems a 50% list size displays properly, so maybe the bottom end of the list view size range can be lowered. :)
> Design matching

- src/tab.rs
Closes: #274
My code comments explain the problem and the fix.
Update: I tagged the wrong issue. Oops.
> fix: Correct range on shift clicking sorted tabs

- i18n/ja/cosmic_files.ftl
Note about "Replace with" being reworded as "Replace with this: "
_In general, please be more liberal with {$name} variables in the future!_
It wasn't impossible to work around, but not every language is Subject-Verb-Object (e.g. I eat poi). Japanese is SOV (I poi eat) and Tagalog is VSO (Eat I poi). Using {$name} variables not only helps give more context about how the string will appear but helps translators word them closer to how they speak and write. This helps avoid writing things such as で開くFirefox when they should be Firefoxで開く
Thank you for reading
> Update cosmic_files.ftl for Japanese

- src/app.rs
If you think the change is acceptable. It kind of is  now similar to how Gnome files behaves,  if you exclude the onChange vs onSubmit difference with regards to searching.  Open issue: #385  
Demo: 
https://github.com/user-attachments/assets/ec8df0bb-0916-4078-9ed1-3c9f262e6961
> Consider clearing the search filtering when searchSubmit and the input is empty.

- Cargo.lock
- Cargo.toml
- i18n/en/cosmic_files.ftl
- src/tab.rs
This subsumes #414. Took feedback into account to display more human-readable permissions. Also, display the owner and group ownership inline with the permissions themselves. 
Decided to put this in a new PR in case the old one is preferred, this one has a bit more going on.
> Display file ownership and permissions.

- src/menu.rs
We discussed this with @pop-os/ux present at this year's summit.
Nautilus, Dolphin, and other file managers have `New folder...` shown first, before `New file...`. Swap them for better muscle memory moving between programs.
> menus: Show new folder option before new file option

- src/app.rs
- src/dialog.rs
- src/tab.rs
Use the freedesktop spec `document-open-recent-symbolic` icon, instead of `accessories-clock-symbolic`.
> [Recents] Use correct icon

- i18n/en/cosmic_files.ftl
- src/tab.rs
Implements  #343
It currently assumes a 12-hour clock for the time format. It would probably make sense to add a setting to be able to switch it to a 24-hour clock. Maybe it could just use whatever is configured for the time applet?
> Change display of date and time

- src/app.rs
This pull request addresses an issue where a toggle in the UI always sent a true value to the component, regardless of the actual toggle state. The fix ensures that the correct value is now passed to the component, reflecting the real state of the toggle.
- fixes #545
> fix(toggle-show-details): fix show-details toggle

- src/operation.rs
This pull request fixes the handling of compound file extensions such as `.tar.gz` and `.tar.bz2`, ensuring that these extensions remain intact at the end of the filename when creating unique copies.
- Added a constant list of compound extensions to check against.
- Enhanced the logic for determining the file stem and extension, particularly for compound extensions.
- Preserved existing behavior for directories and files with standard extensions.
- Ensures that files with compound extensions are handled correctly, preventing issues like incorrect filename formats.
- Please verify that extraction preserves the correct folder names for files with complex extensions and that copy suffixes are appended correctly for existing folders.
> fix(copy_unique_path): fix compound file extension handling

- i18n/en/cosmic_files.ftl
- src/app.rs
- src/mime_app.rs
> Run executables

- src/app.rs
This pull request addresses a bug in the sidebar functionality of Cosmic Files, where users were able to pin the same file or directory multiple times, resulting in duplicate entries.
- fixes #556
> fix(sidebar): prevent duplicate entries of the same item

- src/tab.rs
This pull request modifies the gallery view toggle logic to ensure that it is triggered only when the current selection is an image. The previous implementation toggled the gallery view based on any selected item, which could include non-image files.
- fixes #543
> fix(gallery): trigger gallery view only on images

- src/app.rs
- src/dialog.rs
- src/tab.rs
This updates the keyboard behavior around editing the location to act more like other programs like Nautilus and Firefox. 
When you hit ctrl+l, it immediately allows you to type in the location box. You can de-select the location box by hitting escape or clicking in the tab window.
> Update location edit selection behavior

- src/app.rs
- src/menu.rs
Closes: #593
Trash bins currently show an incorrect menu with invalid actions such as opening the bin in a terminal. The menu also doesn't have an entry for emptying the trash.
> fix: Trash icons should show the trash menu

- src/menu.rs
- src/tab.rs
Fixes #517.
Increased the width of the context menu slightly, to better fit the "Open in new window" item.
<sub>Wasn't able to figure out how to center thumbnails. :(</sub>
> [Context Menu] Use radius from theme

- Cargo.lock
- src/menu.rs
- src/tab.rs
~This is mainly to fix the panic in `cosmic-files-applet` when **Show details** is used on the desktop,~ but also includes minor code cleanup and design matching.
Edit: With the force push, I made the list view rules use the radius of the list items as horizontal padding, so that it always matches the designs (in the sense that the dividers should stop where the curve begins).
> Fix list view styling

- src/tab.rs
This PR updates the style and adds padding to the text editor to match the style in text inputs, text editor is currently using the default iced class.
> Set style and padding for text editor

- src/app.rs
- src/dialog.rs
- src/tab.rs
This centers the text box in gallery view, and removes the usage of `widget::settings::view_column`, since it introduced extra padding in context drawers (which isn't present in the designs).
> Center text gallery previews

- src/tab.rs
Fixes #635 
Should the show_hidden value also be saved to the app config, or is it okay for the value to be reset when starting the application?
> Fix 'Show hidden files' toggle being reset when tab config is updated

- src/app.rs
This PR fixes part of #281 - [comment](https://github.com/pop-os/cosmic-files/issues/281#issuecomment-2423350968)
By use the parent of the file/folder instead of the tab location to create the new file location.
There is still an issue where when renaming a file in the tab location, the search results disappear.
> fix: renaming of searched element

- src/app.rs
resolves #281 - [comment](https://github.com/pop-os/cosmic-files/issues/281#issuecomment-2423350968)
This now checks if a tab currently in search mode and updates search instead of rescanning the tab when an event happens.
It also fixes a bug where when in search some event e.g. rename from another program happens, the search would get cleared.
---
This might make:
https://github.com/pop-os/cosmic-files/blob/3dde3c8fbc5d92bcbfa61f53cb60d14b9b10f1cc/src/app.rs#L2540-L2541
Obsolete, based on my testing it does, but I am not 100% sure.
---
I also thought about introducing a new function that handles the logic to decide if a rescan or a search update needs to happen, and use that function everywhere instead of the rescan. I think this should be a bit more stable than handle each search edge …
> fix: update search on events

- src/dialog.rs
`Subscription::map` must be provided a non-capturing closure. A couple places were passing capturing closures, which caused a debug assert failure. These have been fixed.
Closes #723
> Fix crash for dialog in debug mode

- src/clipboard.rs
This allows the full path of the copied file to be pasted as text into more applications.
Closes #728
> Add more plain text mime types when copying files

- src/tab.rs
Before this fix the following steps would not work correctly:
1. Select a range with shift click.
2. Select a single item that's in the currently selected range, without holding shift.
3. Hold shift and click another item to select a new range.
Instead of the item selected in step 2 being the start or end of the range, the original range from step one is used to get the start or end of the new range.
This fix makes sure the range gets reset when selecting an item in step 2.
> Fix resetting shift select range

- src/operation/mod.rs
- src/operation/recursive.rs
- src/thumbnailer.rs
Fixes Clippy lints for:
* src/thumbnailer.rs
* src/operation/mod.rs
* src/operation/recursive.rs
One fix finished a TODO for Windows by replacing a deprecated function.
I'll work on these in parts so they're easier to review.
> chore(clippy): `thumbnailer.rs`, two files in operation

- examples/copy.rs
- src/app.rs
- src/mounter/mod.rs
- src/mouse_area.rs
- src/operation/controller.rs
- src/tab.rs
Fixes lints for:
* src/operation/controller.rs
* src/mouse_area.rs
* src/mounter/mod.rs
> chore(clippy): `mouse_area`, `controller` & more

- src/mime_app.rs
- src/mounter/gvfs.rs
- src/mouse_area.rs
- src/operation/mod.rs
Fixes Clippy lints for:
* src/mounter/
* src/operation/
* src/mime_app.rs
* src/mouse_area.rs (I missed two of them last time)
> chore(clippy): mime_app, operation, mounter

- i18n/en/cosmic_files.ftl
- src/app.rs
- src/operation/mod.rs
apologies in advance if this is bad/jumping the gun/etc, i'm working for a client who _loves_ sending password protected zips atm, so this was a frequent pain point for me
**changes tl;dr:**
- refactor `operation::Operation::perform` to return `Result<OperationSelection, OperationError>` to bubble up specific errors
- 99% of existing errors bubble up as a `OperationErrorType::Generic(String)`, and implements the `std::fmt::Display` trait, so should be compatible across the board
- optionally ask for password when extracting a zip provides an invalid password error
- optionally ask for password when compressing a zipfile
--
**when extracting:**
- first try to extract normally, however if an `OperationError` with `kind = OperationErrorType::PasswordRequired` is captured, open a new dialog …
> adding in support to extract/compress zip files with passwords

- src/tab.rs
As of this PR, Clippy only raises three warnings. One warning is related to a TODO which I mentioned in the last PR. Another warning involves an unused variable when a feature is disabled.
> chore(clippy): `tab.rs`

- src/main.rs
Similar to https://github.com/pop-os/cosmic-bg
Reduced memory usage on my system from 300+ MB to 40 MB after navigating through a couple directories with images. Allows most memory to be reclaimed when navigating between directories.
> fix: set M_MMAP_THRESHOLD to lower memory usage significantly

- src/tab.rs
fixes #766 
- check if `.hidden` is a _file_ (readable) before trying to read it
- for whatever reason, an infinite loop / denial of service happens (it looks like, under the hood, an `Err` doesn't bubble up properly)
repro:
```
cd ~/
mkdir demo
cd demo
mkdir .hidden
cosmic-files .
```
functionality remains the same for the following scenarios:
- hiding files via a `.hidden` text file;
- other hidden-by-default files/folders (eg: `.git`);
- toggling on/off `View > Show hidden files` both in and out of a folder with hidden files
> Fixing denial of service where a tab tries to read lines from a .hidden directory

- src/app.rs
- src/tab.rs
This sets the max height of the previews to THUMBNAIL_SIZE, to match text previews. Prevents the previews from becoming too large when the desktop details window is resized horizontally, and prevents the scrollable from becoming too long with predominantly vertical images, which makes it harder to quickly see the metadata.
Not sure if a different value than THUMBNAIL_SIZE should be used (since it's calculated using not very related things), but it seems about the right size for now.
Also adds some spacing to the desktop view options, to match designs.
> Set max height for previews

- cosmic-files-applet/src/main.rs
Applies the same fix used in the cosmic-files app.
> fix(applet): set mmap threshold to lower memory usage

- src/app.rs
- src/mouse_area.rs
- src/tab.rs
fixes https://github.com/pop-os/cosmic-files/issues/190
**changes tl;dr**:
- when dragging to select a number of items, mouse movements outside of the of the `Scrollable`/`MouseArea` viewport aren't captured
- we now capture `Event::Mouse(CursorMoved)` in `app.rs` to track global cursor position
- we bubble that event up to the active tab, which will scroll based on where the cursor is relative to the `Scrollable` viewport
this PR works and _could_ be merged into upstream, but it's currently a bit finicky:
- items that would be in the new selection don't get highlighted until you re-enter the viewport of the `Scrollable`;
- the speed is static (set to an arbitrary `5px`), it would be nicer if it was easier to control based off of how close your cursor is to the viewport
(i'll get these …
> adding in drag-scroll functionality when cursor is outside of scrollable viewport

- src/tab.rs
Fixes the issue with thumbnails by explicitly setting the icon widget width to always be the minimum preventing overflow.
Some before-after images are below.
Before:
After:
Before:
After:
I would like to say that there are some other extremes and even in most other ones that are not very visible, that bug is still present if you look close enough.
> Fixes issue #817 with thumbnails

- src/mouse_area.rs
- src/tab.rs
- part of #812 involved adding a subscription to auto scroll
- doing this caused a desync where the virtual cursor was getting updated far more often than the subscription itself
- this meant, unless the cursor was moved back in bounds, when the `DragEnd` event is triggered the amount of selected files was significantly more than actually selected
**steps to replicate**
- open a folder with a lot of items
- begin drag-scrolling
- let go of your mouse when you're out of bounds
https://github.com/user-attachments/assets/241dcf85-0664-443d-b835-056020d8c503
sorry i didnt catch this earlier :(
> Bugfix to how virtual cursor is calculated before DragEnd when drag-scrolling

- src/app.rs
Fixes #834 
Use `matches!` to compare b/w `ContextPage::Preview` as first pressing on "Close" button would fail the equality check b/w `Preview(None, _)` and `Preview(Some(entity),_)`.
This fixes the two clicks needed to close Preview of Selected as first click would update `self.context_page` from `Preview(None,..)` to `Preview(Some,..)` and next click would pass equality and close Preview.
**EDIT:** prev. implementation was changing `self.context_page` from None to Some in `Preview` which fixed the original issue, but the persist preview would still require two clicks to close.
Newer commit fixes original issue + fixes two clicks required on persisted preview as well.
> fix: close selected preview on single click

- src/app.rs
fixes #844 
Extending selections (ctrl+up/down), the header actions vec would get populated for each selection and would result in either additional nav buttons (in original issue) or if continuing to select more, actions would start to disappear completely.
extend actions vec once to prevent adding more header actions for subsequent selections.
> fix: header actions glitch in preview page

- src/app.rs
- src/lib.rs
Closes #487
Fixes some issues with the context menu in the side bar:
- Add "Open in new tab" for Network and Recents
- Only show "Empty Trash" when there is trash
- Remove "Show Details" from all but Path locations since it doesn't actually work for them currently. Maybe support for other location types should be added in the future?
- Implement "Open in new window" for Trash, Recents, and Network
> Context menu fixes

- src/tab.rs
Closes #807 
This makes it so clicking on the name of the current directory (the last item) in the breadcrumbs puts it into edit mode. Before, it wouldn't do anything, because you're already in the dir. Now it does something useful. This change matches the behavior of Gnome Files.
> Edit location when clicking on current directory

- i18n/en/cosmic_files.ftl
- src/app.rs
Fixes #866 
When clicking on a favorite in the sidebar that no longer exists, it will show an error message with the option to remove the broken favorite from the sidebar.
> Handle broken favorites in sidebar

- src/app.rs
- src/dialog.rs
- src/mouse_area.rs
- src/tab.rs
* Fixes for drawing the drag-select rectangle.
* Make sure the rectangle draws within bounds and doesn't draw up into the title bar or other areas of the window.
* When dragging the mouse outside of the bounds of the window, ensure the selection rectangle updates correctly no matter where you drag.
* Fixes for detecting when to auto-scroll when dragging below the bottom. Previously, you would have to drag as far below the window as the difference between the visible height and the total content height before auto-scroll would kick in.
* Add auto-scroll to the dialog.
* Disable drag-select for the dialog when in single file/folder selection mode.
Fixes #877
> Simplify and fix drag selection and auto scroll

- src/tab.rs
There was an issue with the "Single click to open" setting where right-clicking or middle-clicking on a folder would open it. This makes it so only a left single click will open it.
> Fix for right and middle click in single click mode

- src/app.rs
- src/mime_app.rs
- src/tab.rs
Opening multiple selected paths should:
* Launch one app that supports all of the file paths e.g. an image viewer that allows cycling through the selected images
* Launch multiple instances of an app if the app doesn't handle multiple URLs, such as nsxiv
* Launch different apps for a heterogeneous mix of URLs while taking into account the two rules above. For example, launching a mix of paths of images, videos, and text should open the correct apps
I referenced the first patch that tried to implement this, #451, but ended up rewriting it based on comments on the original PR.
> feat: Open multiple files with one/multiple apps

- src/app.rs
Previously this would only work if the root of the unmounted file-system is open in a tab. This also checks for any sub-path.
fixes: #915
> Fix move to home location on unmount

- src/mime_app.rs
Closes: #922, #925, #924
My original patch, #891, mishandled non-trivial Exec keys. The ordering of arguments matters for the keys, such as for Flatpak apps.
> fix: Handle complex Exec keys in desktop entries

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/menu.rs
- src/mime_app.rs
- src/tab.rs
It might be good to define a smaller static width for the collapsed menu bar popup. It would be more use-able, but not a uniform size.
https://github.com/pop-os/libcosmic/pull/851 implements a default smaller popup for the collapsed menu.
> feat: responsive menu bar

- src/tab.rs
Closes: #310
Depends on Byron/trash-rs#120 which implements a function that only checks if the trash is empty or not instead of parsing each item.
> perf: Only enumerate trash items when necessary [Waiting on trash-rs patch]

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/mime_icon.rs
- src/operation/mod.rs
- src/tab.rs
This attempts to detect remote filesystems on Linux using the /proc/self/mountinfo file and checking the filesystem against a hardcoded list of remote filesystems. Remote filesystems will not thumbnail, read file data to determine mime types, or calculate directory sizes.
This potentially resolves the following issues:
- #582
- #741 
- #819
- #823
- #905 (need to find out filesystem name)
> Reduce features used on remote filesystems

- i18n/de/cosmic_files.ftl
- i18n/en/cosmic_files.ftl
- i18n/fr/cosmic_files.ftl
- src/app.rs
- src/dialog.rs
- src/key_bind.rs
- src/menu.rs
- src/operation/mod.rs
- src/tab.rs
I have started this by rebase https://github.com/pop-os/cosmic-files/pull/359 from @dengelt.
And I have modified to handle `shift` modifier in contextual menu option and dialog menu.
As result, I have removed the _now useless_ option to enable/or not  `permanently delete` functionality.
I also rename `Modifiers` message to `ModifiersChanged` as it's directly linked to `KeyEvent::ModifiersChanged`, but I can remove the relative commit if it is preferred.
> feat: add Permanently delete functionnality

- examples/copy.rs
- src/mouse_area.rs
- src/tab.rs
- in the current version, zooming with mouse relies on an `on_scroll` event captured on the `mouse_area`
- if you hold CTRL while inside a mouse area, and then move your cursor out, the state never updates since the key release never reaches the mouse area
- instead, we now use the existing global modifiers to ensure zooming works as expected in this edge case
(also, fixes the `copy` example since it was erroring)
demonstration:
https://github.com/user-attachments/assets/94576f44-18db-4639-8050-a2420880147c
to replicate:
- mouse over a tab
- hold CTRL
- move to the sidebar, or elsewhere in the program (tab header, etc)
- release CTRL
- mouse over a tab again
- try to scroll up/down
> bugfix to zooming where releasing CTRL outside of a mouse_area causes modifier to 'stick'

- i18n/en/cosmic_files.ftl
- i18n/nl/cosmic_files.ftl
*Notice: changes English source language!*
adding a singular and a plural to `operations-running` and `operations-running-finished` within  `# process footer`
> i18n(en) add singular and plural to English and Dutch translations

- src/app.rs
- src/clipboard.rs
- src/operation/recursive.rs
- src/tab.rs
The typos were indicated by `typos` tool : https://github.com/crate-ci/typos/
> simple fix some typos in comment or var name

- src/tab.rs
listing a directory inside a gvfs mount can be currently extremely laggy (ex: `DCIM/Camera` directory on my phone, which has ~1300 items, takes ~25 seconds to list everything)
- use `gio::prelude::FileExt::enumerate_children` to loop through a directory if it's inside a gvfs mount, rather than using `fs::read_dir`
- for gvfs directories, use a new `ItemMetadata::GvfsPath` to allow grabbing some meta directly from gio to avoid seemingly more expensive `fs::` operations
- for gvfs directories, always assume `remote = true` for the purposes of guessing mime types (to avoid having to read the file)
for me, this loads up my `DCIM/Camera` folder in ~75ms instead :D 
this is (mostly) functional, but leaving as a draft until i can fix the following:
> drastically speed up gvfs mount directory listings

- src/app.rs
- src/dialog.rs
- add new `Dialog::create()` method w/ new `DialogSettings` struct
- deprecate `Dialog::new()` in favour of `Dialog::create()`
this allows passing the appid for file dialogs, eg if i'm trying to open a file/folder via an xdg portal it'll currently create a new window with the appid **com.system76.CosmicFilesDialog**. this allows the xdg portal to pass through the appid of the requester, meaning that the windows can stay stacked/associated.
this also provides a more backwards compatible way to add new settings to dialogs in the future
> add ability to pass appid through to file dialogs

- src/tab.rs
- src/thumbnail_cacher.rs
create thumbnail folders if necessary, also if cached thumbnail fails, don't return notimage if the thumbnail is an image.
I accidentally nuked my thumbnail cache and this was necessary, 
can be tested simply by running `rm -rf ~/.cache/thumbnails/*`
> thumbnail: create thumbnail folder and fix bad cache

- src/tab.rs
> fix: exit early from thumbnail generation if file is too big

- src/app.rs
Remove unnecessary watch of sub-directories in trash bins, which causes long startup times.
fixes #970
fixes #823
> Fix slow startup

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/config.rs
- src/dialog.rs
- src/tab.rs
This will allow using jxl-oxide for thumbnail creation, it seems to be working well for me but it's a draft for a couple reasons, the primary one is im not sure the best resource limit to set. I feel like this should be set in a configuration, but even then I don't know what defaults should be used.
the current value I found to be necessary for some of my images, but likely way to high for lower end systems. (that being said, hitting an oom case in cosmic-files is much better then having a thumbnailer oom since oomd will actually kill cosmic-files instead of the entire compositor)
> thumbnail: Support jxl and plumbing for future formats.

- src/tab.rs
This fixes a bug where right-clicking a file while the context menu was open for another file would open another context menu that couldn't be closed.
The new behavior is to close the context menu.
> Fix for right-clicking file when context menu is open already

- i18n/en/cosmic_files.ftl
- src/archive.rs
- src/operation/controller.rs
- src/operation/mod.rs
- src/operation/reader.rs
- src/operation/recursive.rs
- src/tab.rs
Closes: #1157
The fix splits the "canceled" and "failed" states for OperationError. It also preserves that state because some functions overwrote the state by rewrapping the error.
> Fix extracting password protected archives

- src/archive.rs
Calling it on every file massively slows down extraction of zip archives containing a lot of files.
Yields a ~60x time reduction for extracting a zipped folder containing 10,000 empty txt files and about a 20x reduction for extracting niri source code (in a zip).
Makes zip archive extraction time roughly match other formats.
From what I can find, Ark also doesn't seem to do this, and instead relies on the OS to handle it.
> perf(zip): don't call `sync_all()` on every file
